#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bkcharts
Version  : 0.2
Release  : 2
URL      : http://pypi.debian.net/bkcharts/bkcharts-0.2.tar.gz
Source0  : http://pypi.debian.net/bkcharts/bkcharts-0.2.tar.gz
Summary  : High level chart types built on top of Bokeh
Group    : Development/Tools
License  : BSD-3-Clause
Requires: bkcharts-legacypython
Requires: bkcharts-python
Requires: numpy
Requires: six
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
No detailed description available

%package legacypython
Summary: legacypython components for the bkcharts package.
Group: Default

%description legacypython
legacypython components for the bkcharts package.


%package python
Summary: python components for the bkcharts package.
Group: Default
Requires: bkcharts-legacypython

%description python
python components for the bkcharts package.


%prep
%setup -q -n bkcharts-0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1504998461
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1504998461
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)
/usr/lib/python3*/*
